language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
env:
  - CXX=g++-4.8